export const projects = [
  {
    title: 'Starz FYC',
    description: "STARZ originals presents our 2024 FYC (For Your Award Consideration) series. Explore content and watch now via the access code provided by academy or guild.",
    video: '/images/fyc.webm',
    tags: ['NextJS', 'TailwindCSS', 'Zustand', 'AWS Lambda', 'Cloudfront', 'API Gateway', 'Bitbucket', 'Bamboo', 'Jira'],
    source: 'https://github.com/gibstock/redcooler.io',
    visit: 'https://www.starzfyc.com/',
    id: 5,
  },
  {
    title: 'Starz #TAKETHELEAD',
    description: "TakeTheLead is STARZ's commitment to amplifying narratives by, about and for women and underrepresented audiences.",
    video: '/images/takethelead2.webm',
    tags: ['NextJS', 'TailwindCSS', 'Zustand', 'AWS Lambda', 'Cloudfront', 'API Gateway', 'Bitbucket', 'Bamboo', 'Jira'],
    source: 'https://github.com/gibstock/redcooler.io',
    visit: 'https://www.starz.com/takethelead',
    id: 4,
  },
  
  {
    title: 'Starz Brandhub',
    description: "A system where all assets that define our company's branding live.",
    image: '/images/brandhub.png',
    tags: ['NextJS', 'TailwindCSS', 'Zustand', 'AWS Lambda', 'Cloudfront', 'API Gateway', 'Bitbucket', 'Bamboo', 'Jira'],
    source: 'https://github.com/gibstock/top-16-stock-prices',
    visit: 'https://brand.starz.com/',
    id: 3,
  },
  {
    title: 'Starz Style Guides',
    description: "Usage notes, examples, and guidelines for creative assets on each of our STARZ Original Series.",
    image: '/images/styleguide.png',
    tags: ['NextJS', 'TailwindCSS', 'Zustand', 'AWS Lambda', 'Cloudfront', 'API Gateway', 'Bitbucket', 'Bamboo', 'Jira'],
    source: 'https://github.com/gibstock/onk-clothing-storefront',
    visit: 'https://style-guide.starz.com/',
    id: 2,
  },
  {
    title: 'Redcooler.io',
    description: "A website to pair and store your lyrics with music for ease of access. Also a community designed for musicians and writers to discuss and collaborate on projects.",
    video: '/images/redcooler.webm',
    tags: ['NextJS', 'TailwindCSS', 'React-Query','Zustand', 'Appwrite.io'],
    source: 'https://github.com/gibstock/redcooler.io',
    visit: 'https://www.redcooler.net',
    id: 1,
  },
  {
    title: 'The Berghoff',
    description: "Concept for restaurant website rebranding",
    video: '/images/berghoff.webm',
    tags: ['HTML', 'CSS', 'JS','GSAP', 'DigitalOcean'],
    source: 'https://github.com/gibstock/onk-clothing-storefront',
    visit: 'https://agws.app/andre/theberghoff-demo/',
    id: 1,
  },
  // {
  //   title: 'Code Distiller',
  //   description: "Movie Review website where anyone can write a review. Built with Express, deployed to DigitalOcean.",
  //     image: '/images/6.png',
  //     tags: ['NodeJS', 'ExpressJS', 'EJS','MySQL', 'DigitalOccean'],
  //   source: 'https://github.com/gibstock/code-distiller',
  //   visit: 'https://www.codedistiller.com',
  //   id: 6,
  // },
  // {
  //   title: 'E-Commerce',
  //   description: "Fully functional E-Commerce store using Stripe for payment and Sanity.io as a headless content manager.",
  //     image: '/images/1.png',
  //     tags: ['React', 'NextJS', 'Sanity.io','Stripe API', 'Vercel'],
  //   source: 'https://github.com/gibstock/onk-ecommerce',
  //   visit: 'https://onk-ecommerce.vercel.app/',
  //   id: 5,
  // },
  // {
  //   title: 'Hope River - Made for Davis Poet Laureate',
  //   description:"Location activated progressive web app that immerses the user in sound design.",
  //   image: '/images/2.png',
  //   tags: ['PWA', 'HTML', 'CSS', 'JavaScript'],
  //   source: 'private',
  //   visit: 'https://www.agws.app/davis/hope-river',
  //   id: 4,
  // },
  // {
  //   title: 'Real-Time Video Chat',
  //   description: "Real-time video chat web app with text chat and user generated poll.",
  //     image: '/images/3.png',
  //     tags: ['React', 'Agora.io'],
  //   // source: '#',
  //   visit: 'https://kcvidchat.netlify.app/create',
  //   id: 3,
  // },
  // {
  //   title: 'Actor Searching App',
  //   description: "App for quickly looking up movies actors have been in. Consuming my own API.",
  //   image: '/images/4.png',
  //   tags: ['React', 'API', 'Material UI', 'Axios'],
  //   source: 'https://github.com/gibstock/react-what-from-app',
  //   visit: 'https://react-what-from-app.herokuapp.com/',
  //   id: 2,
  // },
  // {
  //   title: 'Get Happy Faces',
  //   description: "Fun game where you try to fill the board with faces before the clock runs out. Features a real-time leaderboard.",
  //   image: '/images/5.png',
  //   tags: ['HTML', 'CSS', 'JavaScript', 'Google Sheets'],
  //   source: 'https://github.com/gibstock/get-happy',
  //   visit: 'https://get-happy.netlify.app/',
  //   id: 1,
  // },
];