export const projects = [
  {
    title: 'ONK E-Commerce',
    description: "Fully functional E-Commerce store using Stripe for payment and Sanity.io as a headless content manager.",
      image: '/images/1.png',
      tags: ['React', 'NextJS', 'Sanity.io','Stripe API', 'Vercel'],
    source: 'https://github.com/gibstock/onk-ecommerce',
    visit: 'https://onk-ecommerce.vercel.app/',
    id: 0,
  },
  {
    title: 'GPS Activated Apps',
    description:"Location activated progressive web app that displays art information around campus.",
    image: '/images/2.png',
    tags: ['PWA', 'HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/design-hub-arc/arc-art-walkabout',
    visit: 'https://arc-art-walkabout-demo.netlify.app/',
    id: 1,
  },
  {
    title: 'Real-Time Video Chat',
    description: "Real-time video chat web app with text chat and user generated poll.",
      image: '/images/3.png',
      tags: ['React', 'Agora.io'],
    source: '#',
    visit: 'https://kcvidchat.netlify.app/create',
    id: 2,
  },
  {
    title: 'Actor Searching App',
    description: "App for quickly looking up movies actors have been in. Consuming my own API.",
    image: '/images/4.png',
    tags: ['React', 'API', 'Material UI', 'Axios'],
    source: 'https://github.com/gibstock/react-what-from-app',
    visit: 'https://react-what-from-app.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Get Happy Faces',
    description: "Fun game where you try to fill the board with faces before the clock runs out. Features a real-time leaderboard.",
    image: '/images/5.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'Google Sheets'],
    source: 'https://github.com/gibstock/get-happy',
    visit: 'https://get-happy.netlify.app/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey', },
  { year: 2019, text: 'Completed Udemy ZTM Course', },
  { year: 2020, text: 'Retired from bartending to focus on coding', },
  { year: 2021, text: 'Started internship with the Design Hub', },
  { year: 2022, text: 'Started my own freelance business', },
];