export const projects = [
  {
    title: 'Stock Chops',
    description: "A single page app to track stocks on the US Exchange",
      image: '/images/stock-chops.png',
      tags: ['NextJS', 'TailwindCSS', 'React-Query','Zustand', 'Finnhub.io'],
    source: 'https://github.com/gibstock/top-16-stock-prices',
    visit: 'https://www.stockchops.com',
    id: 8,
  },
  {
    title: 'The Berghoff',
    description: "Demo website for restaurant rebranding",
      image: '/images/7.png',
      tags: ['HTML', 'CSS', 'JS','GSAP', 'DigitalOcean'],
    source: 'https://github.com/gibstock/onk-clothing-storefront',
    visit: 'https://agws.app/andre/theberghoff-demo/',
    id: 7,
  },
  // {
  //   title: 'Code Distiller',
  //   description: "Movie Review website where anyone can write a review. Built with Express, deployed to DigitalOcean.",
  //     image: '/images/6.png',
  //     tags: ['NodeJS', 'ExpressJS', 'EJS','MySQL', 'DigitalOccean'],
  //   source: 'https://github.com/gibstock/code-distiller',
  //   visit: 'https://www.codedistiller.com',
  //   id: 6,
  // },
  {
    title: 'E-Commerce',
    description: "Fully functional E-Commerce store using Stripe for payment and Sanity.io as a headless content manager.",
      image: '/images/1.png',
      tags: ['React', 'NextJS', 'Sanity.io','Stripe API', 'Vercel'],
    source: 'https://github.com/gibstock/onk-ecommerce',
    visit: 'https://onk-ecommerce.vercel.app/',
    id: 5,
  },
  {
    title: 'Hope River - Made for Davis Poet Laureate',
    description:"Location activated progressive web app that immerses the user in sound design.",
    image: '/images/2.png',
    tags: ['PWA', 'HTML', 'CSS', 'JavaScript'],
    source: 'private',
    visit: 'https://www.agws.app/davis/hope-river',
    id: 4,
  },
  {
    title: 'Real-Time Video Chat',
    description: "Real-time video chat web app with text chat and user generated poll.",
      image: '/images/3.png',
      tags: ['React', 'Agora.io'],
    // source: '#',
    visit: 'https://kcvidchat.netlify.app/create',
    id: 3,
  },
  // {
  //   title: 'Actor Searching App',
  //   description: "App for quickly looking up movies actors have been in. Consuming my own API.",
  //   image: '/images/4.png',
  //   tags: ['React', 'API', 'Material UI', 'Axios'],
  //   source: 'https://github.com/gibstock/react-what-from-app',
  //   visit: 'https://react-what-from-app.herokuapp.com/',
  //   id: 2,
  // },
  // {
  //   title: 'Get Happy Faces',
  //   description: "Fun game where you try to fill the board with faces before the clock runs out. Features a real-time leaderboard.",
  //   image: '/images/5.png',
  //   tags: ['HTML', 'CSS', 'JavaScript', 'Google Sheets'],
  //   source: 'https://github.com/gibstock/get-happy',
  //   visit: 'https://get-happy.netlify.app/',
  //   id: 1,
  // },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey', },
  { year: 2019, text: 'Completed Udemy ZTM Course', },
  { year: 2020, text: 'Retired from bartending to focus on coding', },
  { year: 2021, text: 'Started internship with the Design Hub', },
  { year: 2022, text: 'Started my own freelance business', },
];